version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/www:/var/www
  npm:
    image: verdaccio/verdaccio:4.0.0-beta.8
    ports: 
      - 4873:4873
    volumes: 
      - ./npm/packages:/verdaccio/storage
      - ./npm/conf:/verdaccio/conf
