name: mac
include:
  # - ./services/bytebase.yaml
  - ./services/mysql.yaml
  - ./services/elasticsearch.yaml
  - ./services/skywalking.yaml
  - ./services/superset.yaml

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: sTr0NGp4ssw0rd
    networks:
      - shiwu
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shiwu

  traefik:
    container_name: traefik
    image: traefik:v2.3.6
    ports:
      - 80:80
      - 443:443
    networks:
      - shiwu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ${PWD}/traefik:/etc/traefik # Traefik static config
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"

networks:
  shiwu:
    external: true