version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.3.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ${PWD}/traefik:/etc/traefik # Traefik static config
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.${MAIN_DOMAIN}`)"
  flow:
    container_name: flow
    image: nodered/node-red
    volumes:
      - ./flow:/data
    labels:
      # 设置Host 为 flow.${MAIN_DOMAIN} 进行域名访问
      - "traefik.http.routers.flow.rule=Host(`flow.${MAIN_DOMAIN}`)"
  nginx:
    container_name: global-nginx
    restart: always
    image: openresty/openresty:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/sites:/var/www/html
  pdns-admin:
    container_name: pdns-admin
    image: ngoduykhanh/powerdns-admin
  #   labels:
  #     # 设置Host 为 flow.${MAIN_DOMAIN} 进行域名访问
  #     - "traefik.http.routers.flow.rule=Host(`pdns.${MAIN_DOMAIN}`)"
  #   volumes: 
  #     - ./dns/:/pdns/
    depends_on:
      - pdns
    ports:
      - 9191:80
    environment: 
      - SECRET_KEY='a-very-secret-key'
  #     - SQLALCHEMY_DATABASE_URI=sqlite:////pdns/pdns.sqlite
  pdns: 
    container_name: pdns
    build: ./dns
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 8081:8081
    environment:
      - PDNS_LOG_LEVEL=0
      - PDNS_API_KEY=34H5G34J5H43H34
      - PDNS_WEBSERVER_PASSWORD=123456
      - PDNS_WEBSERVER_ALLOWED_FROM=127.0.0.1,::1,172.0.0.0/8
    volumes: 
      - ./dns/:/pdns/