version: "2.0"

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/mime.types/etc/nginx/mime.types
      - ./nginx/logs:/var/log/nginx
      - ./nginx/sites:/var/www/html
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=luojie
      - MARIADB_USERNAME=luojie
      - MARIADB_PASSWORD=luojie
      - MARIADB_DATABASE=dev
    volumes:
      - ./mariadb:/var/lib/mysql
  # nginx-proxy:
  #   image: jc21/nginx-proxy-manager-base:latest
  #   ports:
  #     # - 80:80
  #     # - 81:81
  #     # - 43:443
  #   environment:
  #     - NODE_ENV=development
  #     - FORCE_COLOR=1
  #   volumes:
  #     - ./nginx/proxy/data:/data
  #     - ./nginx/proxy/data/letsencrypt:/etc/letsencrypt
  #     - ./nginx/proxy/app:/app
  #     - ./nginx/proxy/app/rootfs/etc/nginx:/etc/nginx
  #   working_dir: /app
  #   command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js
