providers:
  file:
    directory: /etc/traefik/config
    filename: /etc/traefik/config/config.yml
    watch: true
  docker: {}

entryPoints:
  http:
    # Listen on port 8081 for incoming requests
    address: :80
  https:
    address: :443

api:
  dashboard: true
  insecure: true

log:
  # If something goes wrong, changing this to `DEBUG` might help you finding
  # out what happens.
  level: "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format: "common"

accessLog:
  filePath: "/etc/traefik/logs/access.log"
