services:
  mysql:
    image: mariadb
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-replica-main:/tmp
      - /db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: &mysql-default-environment
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: uadme
      MYSQL_USER: uadme
      MYSQL_PASSWORD: abc123
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    restart: always
    networks:
      - shiwu
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 10s
      retries: 10
  mysql-slave:
    image: mariadb
    container_name: mysql-slave
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    depends_on:
      - mysql
    volumes:
      - mysql-replica-read:/tmp
    environment: *mysql-default-environment
    networks:
      - shiwu
    ports:
      - "3307:3306"

volumes:
  mysql-replica-main:
  mysql-replica-read:
