version: "2.0"

services:
  # npm:
  #   container_name: npm
  #   image: verdaccio/verdaccio:4.0.0-beta.8
  #   ports:
  #     - 4873:4873
  #   volumes:
  #     - ./npm/packages:/verdaccio/storage
  #     - ./npm/conf:/verdaccio/conf
  # mongo:
  #   image: mongo:3.5
  #   volumes:
  #     - type: bind
  #       source: ./mongo/data/db
  #       target: /data/db
  yapi:
    image: branchzero/yapi:1.3.8
    command: /bin/bash -c "[ ! -e /home/yapi/log/init.lock ] && npm run install-server && touch /home/yapi/log/init.lock; npm run start"
    links:
      - mongo:mongo
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./yapi/config.json
        target: /home/yapi/config.json
      - type: bind
        source: ./yapi/log
        target: /home/yapi/log
